# Generated by Django 2.1.4 on 2019-01-01 08:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(default=0)),
                ('buildDate', models.DateTimeField(auto_now=True)),
                ('maxScore', models.IntegerField(default=0)),
                ('holdDices', models.CharField(max_length=10)),
                ('diceNumber', models.IntegerField(max_length=1)),
                ('maxRoll', models.IntegerField(default=4)),
                ('playCount', models.IntegerField(default=0)),
                ('averageScore', models.FloatField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='create', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
