# Generated by Django 2.1.4 on 2019-01-01 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IE', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='name',
            field=models.CharField(default='TEST', max_length=50),
        ),
        migrations.AlterField(
            model_name='game',
            name='diceNumber',
            field=models.IntegerField(default=1),
        ),
    ]
