# Generated by Django 2.1.4 on 2018-12-31 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userName', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('sex', models.CharField(max_length=10)),
                ('birthDate', models.DateField()),
                ('firstName', models.CharField(max_length=50)),
                ('lastName', models.CharField(max_length=50)),
                ('photo', models.FileField(upload_to='')),
                ('email', models.EmailField(max_length=254)),
                ('numberOfAllGames', models.IntegerField(max_length=4)),
                ('averageOfGameScore', models.FloatField(max_length=4)),
                ('averageOfUserScore', models.FloatField(max_length=100)),
            ],
        ),
    ]
