# Generated by Django 2.1.4 on 2019-01-01 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserManagment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='isAdmin',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='numberOfAllGames',
            field=models.IntegerField(null=True),
        ),
    ]
