# Generated by Django 2.1.4 on 2018-12-31 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserManagment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='averageOfGameScore',
            field=models.FloatField(max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='averageOfUserScore',
            field=models.FloatField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='numberOfAllGames',
            field=models.IntegerField(max_length=4, null=True),
        ),
    ]
